# Docsy Jekyll Configuration for Telegram Bot Manager Documentation
title: "Telegram Bot Manager Documentation"
description: "Пользовательская документация для Telegram Bot Manager - современной SaaS-платформы для создания и управления Telegram ботами"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://surnin.github.io/bot-platform-user-docs" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: vsoch/docsy-jekyll

# Plugin configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# SEO settings
lang: ru
author: "Telegram Bot Manager Team"
email: "support@telegram-bot-manager.com"

# GitHub repository settings
repo: "https://github.com/surnin/bot-platform-user-docs"
github_user: "surnin"
github_repo: "bot-platform-user-docs"
github_branch: "main"

# Social links for Docsy theme
twitter: ""
linkedin: ""
dockerhub: ""

# Theme customization
color: "#667eea"
logo_pixels: 34
feedback: true

# Collections for documentation
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults for different content types
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - CHANGELOG.md
  - LICENSE

# Include files in build
include:
  - _pages

# Social links
social:
  github: "surnin/telegram-bot-manager"
  email: "support@telegram-bot-manager.com"

# Analytics (optional)
# google_analytics: G-XXXXXXXXXX

# Custom variables
version: "1.2.0"
main_repo: "https://github.com/surnin/telegram-bot-manager"
demo_url: "https://demo.telegram-bot-manager.com"